[project]
name = "damdesign"
version = "0.1.0"
description = "An approach to analyzing and designing concrete gravity dams with the single-step method"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
]
author = "kolahimself"
